"""empty message

Revision ID: 39feec187b33
Revises: 
Create Date: 2024-10-06 18:15:19.036446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39feec187b33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('aplication', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('happy', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('overall', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('project', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('services', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('caption', sa.String(), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('role')
        batch_op.drop_column('company_name')
        batch_op.drop_column('phone')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('caption')
        batch_op.drop_column('services')
        batch_op.drop_column('project')
        batch_op.drop_column('time')
        batch_op.drop_column('overall')
        batch_op.drop_column('happy')
        batch_op.drop_column('aplication')
        batch_op.drop_column('product')

    # ### end Alembic commands ###
